### ISSUE TITLE
Appending children without colspan property results in wrong layout

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-form-layout#117]
Can be reproduced in the [basic demos](https://cdn.vaadin.com/vaadin-form-layout/2.1.4/demo/#form-layout-basic-demos) with the following code:

```
var item = document.createElement('vaadin-text-field');
item.setAttribute('label','New Field');
item.setAttribute('value','New Value');
//item.setAttribute('colspan','');
$0.appendChild(item);
```
Result looks like this:
![image](https://user-images.githubusercontent.com/9820084/61780411-229b7f00-ae0b-11e9-8429-7c43f62461e2.png)

And in the [Form Item demo](https://cdn.vaadin.com/vaadin-form-layout/2.1.4/demo/#form-layout-form-item-demos) with the following code:

```
var item = document.createElement('vaadin-form-item');
item.innerHTML = `<label slot="label" for="newqnput">New Field</label><input id="newqnput" class="full-width" value="NewValue">`
//item.setAttribute('colspan','');
$0.appendChild(item); // $0 is vaadin-form-layout
```
Result looks like this:
![image](https://user-images.githubusercontent.com/9820084/61780469-3cd55d00-ae0b-11e9-9fe5-d537eb68ade5.png)

Workaround:
* In both cases setting the `colspan` attribute fixes the issue

**Comment by yuriy-fix** [comment]
I guess it can be fixed by simply removing the check over here: https://github.com/vaadin/vaadin-form-layout/blob/8388e4c95db552f8f458efd8a64d512afcb642e9/src/vaadin-form-layout.html#L314
However, it seems that the check for `colspan` was added intentionally: 
https://github.com/vaadin/vaadin-form-layout/pull/92#pullrequestreview-151795290 (The first comment by Anton)

**Comment by DiegoCardoso** [comment]
> However, it seems that the check for `colspan` was added intentionally

I think that the check on `colspan` is valid for the `MutationObserver`, because form layout is only interested on changes of its direct children. However, it's probably worth to recalculate styles when a new child is added, no matter if it has `colspan` or not.

Also, I noticed that since only the added nodes are being checked, removing a node leads to incorrect layout. Maybe it's also worth verifying that and invoke the styles update on that case as well.

Any thoughts?

**Comment by platosha** [comment]
@DiegoCardoso agree, it seems worth to update styles on every child addition and removal.
