### ISSUE TITLE
`vaadin-form-item` should be `vaadin-form-layout-item`?

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#33]
To be consistent with other components

(This is the DX tests finding)

**Comment by platosha** [comment]
Arguments against:

- Would make CSS props longer: `--vaadin-form-layout-item-label-width` vs `--vaadin-form-item-label-width`
- The CSS properties of the item should be targeted for the item element specifically. Defining the item CSS properties for the parent `<vaadin-form-layout>` element would not work in all the browsers due to a limitation in the ShadyCSS Scoping Shim. Using the `--vaadin-form-item` prefix instead of `--vaadin-form-layout-item` makes it more clear that these are the CSS properties of the item and not of the layout.
