### ISSUE TITLE
Multiple Columns

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-form-layout#5]
Specs by @jouni

Trying to keep this somewhat simple for now. This is again just my proposal, and I appreciate feedback about the shortcomings or problems in this spec.

# Columns

The form layout is divided into a number of columns. By default, there are 2 columns, but the developer can control this per form-layout using a property (e.g. `columns`).

The column widths are equal and in total span the width of the form-layout.

There is a gap between the columns, which can be controlled with a CSS custom property (e.g. `--vaadin-form-layout-column-gap`). The default is `2em`.

### Default column layout with 6 fields:

```html
<vaadin-form-layout>
  <vaadin-text-field label="First Name"></vaadin-text-field>
  <vaadin-text-field label="Last Namel"></vaadin-text-field>
  <vaadin-text-field label="Email address"></vaadin-text-field>
  <vaadin-text-field label="Telephone number"></vaadin-text-field>
  <vaadin-text-field label="Department"></vaadin-text-field>
  <vaadin-text-field label="Number of responsibilities"></vaadin-text-field>
</vaadin-form-layout>
```

![2cols](https://cloud.githubusercontent.com/assets/66382/24449946/b15968f4-1481-11e7-9415-c93aaae2d510.png)
![2cols-redlines](https://cloud.githubusercontent.com/assets/66382/24449950/b4f4b4e6-1481-11e7-9ce2-c911322aac8d.png)

**Note**, that here the field width is the size specified by the field element or the developer.

### Column count increased to 3, and the same HTML markup:

```html
<vaadin-form-layout columns="3">
  ...
</vaadin-form-layout>
```
![3cols](https://cloud.githubusercontent.com/assets/66382/24450779/d4bd5582-1484-11e7-8178-c3d07afee23e.png)

**Note**, that here the field width is being constrained by the form item width, i.e. the field has a max-width of 100% inside the form item.

### Column count decreased to 1, and the same HTML markup:

```html
<vaadin-form-layout columns="1">
  ...
</vaadin-form-layout>
```
![nocols](https://cloud.githubusercontent.com/assets/66382/24454173/8f9afef0-1493-11e7-927b-7e264ff063f1.png)

# Column spanning

The developer can instruct a form item to span multiple columns by defining a CSS custom property for the form item (e.g. `--vaadin-form-layout-colspan`).

Colspan values larger than the column count are reduced to match the column count.

## Example

```html
<vaadin-form-layout>
  <!-- Same 6 fields from before -->
  ...
  <vaadin-text-area label="Notes" style="--vaadin-form-layout-colspan: 2;"></vaadin-text-area>
</vaadin-form-layout>
```
![colspan](https://cloud.githubusercontent.com/assets/66382/24451738/b3e79c60-1488-11e7-88a4-dd83f755eda6.png)

# Responsiveness

The responsive behavior of the columns is specified in #4.

# Label

In the mockups of this ticket, the label should be on top of the input box (as in default `<vaadin-text-field>`). Moving the labels aside is specified in #9.

**Comment by jouni** [comment]
I’ll comment here instead of the PRs, as this is more general and not specific to the PR implementations.

My mental model for this goes as follows:
- I want a layout where field labels are on the side of the field instead of on top. If I don’t have this requirement, I could just use some other layout or grid system directly. So having to think about a 12-column layout doesn’t really match my expectation.
- I want the space for labels to be equally wide, i.e. there should be a “label column”. The width of that label should be as wide as the widest label I have in the layout/form. I can specify a max-width for the labels if I want to. There might be a default max-width also, but I usually don’t need to care about this, the defaults just work most of the time. So again, having to think about “colspan” here does not match my expectation.
- If I haven’t specified any explicit widths for a field, it should use it’s default width, including min and max-widths. I would not expect the layout to touch those by default. The only exception might be to never let the field overflow the layout, so having a max-width of 100%, kind of, would be okay, if I can override that.
- In some cases I want to lay out my fields (including their labels) side-by-side in multiple columns, and sometimes a field should span multiple columns. Here “colspan” starts to make sense.
- When there is not enough space, fields should start to be stacked on top of each other, and usually I don’t need to care about how they are stacked in the end, as long as the grouping I have specified holds up (semantic order of the fields and sections, basically).

Now I started to think, isn’t the new vaadin-board element pretty much what we want here, with its common layout variations of 1/2/3/4 columns that wrap in a certain way? The only thing we would add, is the feature that labels are on the side, and that for any matching “columns” (on any row of the layout/board) the label width is equal (dictated by the longest label in that “column”).

See the [vaadin-board demo](http://demo.vaadin.com/vbd/#/row-types) for the different column configurations it offers and how the responsiveness works for those column configurations.

I made some examples quickly that hopefully illustrate the behavior a little. It doesn’t contain all the different row types vaadin-board offers, and the column widths aren’t perfectly distributed: https://www.figma.com/file/fDtZFb2hufzDFQ1xcOib6E9V/form-layout

An extra feature a developer might appreciate is some class to make the “slot” outlines visible for easier debugging.

**Comment by jouni** [comment]
Updated the specs in the description.

**Comment by jouni** [comment]
Updated the specs to include “column count 0” (a.k.a. wrap labels on top of the field).

**Comment by platosha** [comment]
According the column count of 0, this approach would not allow developers to have labels on top and multiple columns at the same time. Instead, I’d suggest the label wrapping threshold as a separate property.

For example, `labelColumnThreshold="20em"`, meaning when the form-layout width is < 20em, the labels are on top.
