### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-form-layout#6]
Quotes by @jouni from vaadin/vaadin-core-elements#58:

> It should be possible to divide the overall form into sections using section headers/dividers.

**Comment by jouni** [comment]
I feel this should be as simple as adding header elements (or any block level elements basically) between the form fields, and by default those headers should “span” the whole layout and force a line break.

See the mockup for an example: https://www.figma.com/file/fDtZFb2hufzDFQ1xcOib6E9V/form-layout

**Comment by jouni** [comment]
One additional feature request is that it should be possible to style the section container, e.g. set a background color and some padding for it.

But this can be a feature we add later, as I’m not 100% sure how section paddings should work. Section padding should probably be shared between all sections of the form layout, so that label widths still match across sections.

**Comment by jouni** [comment]
For the first version, I think it’s enough to support additional header labels between the sections. Other styling options can be added later if needed.

**Comment by jouni** [comment]
I’m deprioritizing this issue for now (moving to inbox), as it’s currently placed in our +6 months backlog.

**Comment by jouni** [comment]
Closing for now. Please add comments if there are some use cases related to form sections that can’t be implemented easily with the current feature set.
