### ISSUE TITLE
Single click selects all text inside paper-input

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#7]
Can be reproduced in `demo/index.html`:

![recorded](https://cloud.githubusercontent.com/assets/6059356/24197313/cfbeb8d0-0f09-11e7-84e1-efca60bbea18.gif)

(Linux/Chrome)

**Comment by samiheikki** [comment]
Did a fresh `bower install` and unable to reproduce the issue. Probably due to https://github.com/PolymerElements/paper-input/issues/529 which was fixed in here: https://github.com/PolymerElements/paper-input/pull/537.

PS paper-inputs are not visible in the cdn master site (404) ping @tomivirkki : https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-form-layout/demo/#form-layout-basic-demos

**Comment by limonte** [comment]
> Did a fresh bower install and unable to reproduce the issue. Probably due to PolymerElements/paper-input#529 which was fixed in here: PolymerElements/paper-input#537.

It seems that you're right, it was fixed.
