### ISSUE TITLE
Provide a simple API for label positioning

### ISSUE THREAD

**Issue by ripla** [vaadin/vaadin-form-layout#99]
Use case: I have multiple form layouts on a page, and I want all the labels to be on top of the field, instead of the left side. Optimally, I'd like this to be an attribute on the main `vaadin-form-layout` element.

**Comment by rolandoisidoro** [comment]
Since label positioning in the `FormLayout` is currently attached to the set of defined `ResponsiveSteps` , I worked around it by creating a few util classes that extend `FormLayout` in which I setup the label positioning. 

#### `SingleColumnFormLayout extends FormLayout`
```
setResponsiveSteps(new ResponsiveStep("0", 1, ResponsiveStep.LabelsPosition.TOP));
```

#### `DoubleColumnFormLayout extends FormLayout`
```
setResponsiveSteps(
        new ResponsiveStep("0", 1, ResponsiveStep.LabelsPosition.TOP),
        new ResponsiveStep("40em", 2, ResponsiveStep.LabelsPosition.TOP)
);
```

**Comment by web-padawan** [comment]
Extending is actually a correct way to implement this feature.
Note, in the web component this can be done like this:

```js
class CustomFormItem extends customElements.get('vaadin-form-item') {
  ready() {
    super.ready();
    this.setAttribute('label-position', 'top')
  }
}
customElements.define('custom-form-item', CustomFormItem);
```

As long as this is doable also in Java, as shown above, I don't think we want to implement this.
